### ISSUE TITLE
性能

### ISSUE THREAD

**Issue by hz9527** [initialdmg/blog#2]
个人看法，不一定对

## 关于base64
如果一个icon反复使用可以考虑字体图标方式，毕竟很多icon都是已字节数量级的，如果变成图片（svg），网络请求带来的开销反倒会更大。  
至于一开始没用到的完全可以使用异步加载模块来实现  
另外css一般来说不阻塞渲染，不过对于单页来说算是阻塞，但是没关系，因为请求会并行发出，毕竟最大的开销一般都是网络。  

## 关于内存回收
有些细节可能不太对，回收机制其实是依赖js引擎来实现。  
其实用了模块打包器后大部分内存管理都是和闭包相关的。  
所以意外的全局变量其实已经可以避免了  
定时器使用匿名函数后就基本可以解决  
意外的dom其实是其次，个人认为最大的问题是 dom 和 事件回掉的问题。在红宝书里有这样的介绍，每次绑定事件 UI 线程 会和 js执行线程建立一个连接，如果dom销毁了事件没移除其实这个连接一直存在。至于dom销毁但被保存了其实也还好，首先 dom 底层其实是 getter实现（个人理解，不一定）也可能是类似 WeakMap 机制

**Comment by initialdmg** [comment]
谢谢提醒，成文仓促，确有一些需要仔细揣度之处。

**base64**

- 关于base64图片的问题，我同意字体图标的方式更好，也对开发人员更为友好。
- 我觉得base64图片在良好的代码组织（如BEM）下，也是一种很好的方式；这里想要说的是不好的编程习惯，如滥用 scoped style 加上 base64 转换，我认为这会带来不必要的消耗。
- 未用到的图片在代码分割、使用异步加载后当然也不会影响当前页面的加载。
- SVG 图片我认为可以适量使用，如公司、产品logo以及一些需要考虑高分辨率场景的应用。
- 对于后面说到的CSS阻塞渲染一说我需要更正，文中要表达的本意是CSS加载对整个流程的阻塞。

**内存回收**

- 内存回收由引擎来自动处理，绝大部分需要手动干预内存回收的问题来源于闭包
- 定时器这一段我现在看来觉得有点混乱，我觉得应该表述为内存问题可能来源于定时器内的调用函数，另一方面遗漏的定时器造成不必要的CPU消耗，另外定时器我觉得定时器**可能**会影响GC时机。

使用匿名函数来解决定时器内存问题的原理我不是特别理解，还请进一步为我解答一下。谢谢

**Comment by hz9527** [comment]
再次看了下，好像你给的例子主要是 interval，现在很少用 interval，基本是 timeout来做。  
正如你写的 ‘无法达到的对象’，那么timeout执行完，匿名函数就是 无法达到的对象，就会被回收

**Comment by initialdmg** [comment]
如果是 `setTimeout` 我就明白了。我也很少用到 `setInterval` 🤝
